Added support for a bunch of popular alternative search engines
psidex/CustomBangSearch pull request #20
Opened 2022-12-07 21:47 UTC by vankessel

Support for ecosia, brave, swisscows, metager, mojeek, and two top searx instances.

2022-12-12 20:13 UTC, psidex commented
Hi! Thanks for the PR, I'll take a look and try and get it merged in soon 😄

2022-12-15 02:18 UTC, psidex requested changes
Looks good other than that! I would appreciate if you could update the readme line that says "This currently only works if you have Google, [etc]" to something that represents the engines it supports now 😄

2022-12-15 02:18 UTC, psidex commented on src/scripts/main.ts
> +  } else if (queryParam === null) {
After some brief testing it seems this should be

```suggestion
  }
  if (queryParam === null) {
```

2022-12-15 02:18 UTC, psidex commented on src/scripts/main.ts
> +        '*://*.swisscows.com/*',
swisscows doesn't seem to work, please investigate or remove this domain from the PR

2022-12-24 02:01 UTC, vankessel commented
Thanks for the review. I had tested it from the search bar not the homepages so I missed the swisscows POST case. I'll fix it up after Christmas. Happy holidays and new year!

2022-12-24 17:27 UTC, psidex commented
Ah yes I did the opposite test! Yeah no worries, take your time :) Happy holidays!

2023-01-17 22:38 UTC, vankessel commented
I've removed Swisscows since I couldn't get it to work. Each request from the homepage does multiple requests of type 'xmlhttprequest' which gets blocked by the early return `r.type !== 'main_frame'`, and it's not as simple as allowing those requests past that check.

2023-01-21 11:27 UTC, psidex approved these changes

2023-01-21 11:27 UTC, merged

2023-01-21 11:28 UTC, psidex commented
LGTM, Thanks! I'll try to get an update pushed to ff / chrome stores this week

2023-02-01 21:55 UTC, psidex commented
Sorry for the wait @vankessel @i-report-bugs, I've just submitted 0.9.5 to the Firefox & Chrome stores, should be available soon!